spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp

  datasource:
    url: jdbc:h2:tcp://localhost/~/photogram
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: update #create, update, none
    properties:
      hibernate:
#        show_sql: true
        format_sql: true

logging.level:
  org.hibernate.SQL: debug
# org.hibernate.type: trace

servlet:
  multipart:
    enabled: true
    max-file-size: 2MB

file:
  path: /Desktop/Spring/spring-3/upload/